baseURL = "https://mynewhugosite.com"
title = "Health and Care Analytics conference"
theme = "HACA_Theme"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "HACA 2025 Registration"
    name = "Registration"
    url = "/HACA_Registration"
    weight = 10

  [[menu.main]]
    identifier = "HACA 2025 Abstracts"
    name = "Abstracts"
    url = "/HACA_Abstracts"
    weight = 20

    [[menu.main]]
      identifier = "HACA 2025 Programme"
      name = "Programme"
      url = "/HACA_Programme"
      weight = 30

      [[menu.main]]
        identifier = "Past Conferences"
        name = "Past Conferences"
        url = "/HACA_Past_Conferences"
        weight = 40
      
[params]

# Social media links

  [[params.social]]
    icon = "youtube"
    icon_pack = "fab"
    url = "https://www.youtube.com/@HACA_Conference"

  [[params.social]]
    icon = "github"
    icon_pack = "fab"
    url = "https://github.com/The-Strategy-Unit/HACA_Site"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fab"
    url = "https://www.linkedin.com/company/haca-live/"

